# Generated by Django 3.2 on 2024-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0008_alter_facility_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("유치원", "유치원"),
                    ("초등학교", "초등학교"),
                    ("중학교", "중학교"),
                    ("고등학교", "고등학교"),
                    ("주민센터", "주민센터"),
                    ("병원", "병원"),
                    ("약국", "약국"),
                    ("은행", "은행"),
                    ("편의점", "편의점"),
                    ("버스정류장", "버스정류장"),
                    ("주유소", "주유소"),
                    ("노인복지시설", "노인복지시설"),
                    ("볼링장", "볼링장"),
                ],
                help_text="시설 구분",
                max_length=50,
                null=True,
            ),
        ),
    ]
