# Generated by Django 3.2 on 2024-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="아파트명")),
                ("address", models.CharField(max_length=100, verbose_name="주소")),
                ("lat", models.FloatField(verbose_name="위도")),
                ("lng", models.FloatField(verbose_name="경도")),
            ],
            options={
                "verbose_name": "아파트",
                "verbose_name_plural": "아파트",
            },
        ),
    ]
