# Generated by Django 3.2 on 2024-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="area",
            field=models.FloatField(default=1, verbose_name="평수"),
        ),
        migrations.AddField(
            model_name="apartment",
            name="built_year",
            field=models.IntegerField(default=2020, verbose_name="준공년도"),
        ),
        migrations.AddField(
            model_name="apartment",
            name="households",
            field=models.IntegerField(default=1, verbose_name="세대수"),
        ),
        migrations.AddField(
            model_name="apartment",
            name="price",
            field=models.IntegerField(default=0, verbose_name="가격"),
        ),
        migrations.AddField(
            model_name="apartment",
            name="room_count",
            field=models.IntegerField(default=1, verbose_name="방 개수"),
        ),
    ]
